#!/usr/bin/env bash
# tests/render/test_render.sh — scenarios for scripts/caped-render.py.
#
# Each scenario builds a throwaway repo in mktemp with fixture commits that
# carry the lifecycle trailers (Idea:/Change:/Archives:), then runs the real
# `caped.sh render` from the project under test (the script resolves the repo
# root via git rev-parse, so the fixture itself needs no caped scripts).
#
# Scenario names carry the [#<slug>] marker of the requirement they cover
# (root README, "Производные view").
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "$0")/../.." && pwd)"
CAPED="$REPO_ROOT/scripts/caped.sh"

pass=0; fail=0
ok()  { printf 'PASS %s\n' "$1"; pass=$((pass + 1)); }
bad() { printf 'FAIL %s\n' "$1"; fail=$((fail + 1)); }

TMP="$(mktemp -d)"
trap 'rm -rf "$TMP"' EXIT
n=0

new_repo() { # fresh repo inside $TMP, cd into it
  n=$((n + 1))
  local dir="$TMP/repo$n"
  mkdir -p "$dir"
  cd "$dir"
  git init -q
  git config user.email test@caped.dev
  git config user.name "caped test"
  printf 'root\tREADME.md\tenforced\tREADME.md\n' > caped.registry
  printf '# fixture\n' > README.md
  git add -A
  git commit -qm seed
}

add_idea() { # <name> <summary> — ideas/<name>.md with frontmatter, no commit
  mkdir -p ideas
  cat > "ideas/$1.md" <<EOF
---
name: $1
summary: $2
priority: high
---
EOF
}

commit_msg() { # <message...> — commit all staged with trailers as given
  git commit -qF -
}

expect_out() { # <name> <args...> — run render, succeed, output in $OUT
  local name="$1"; shift
  set +e
  OUT="$(bash "$CAPED" render "$@" 2>&1)"; RC=$?
  set -e
  if [ "$RC" -eq 0 ]; then ok "$name"
  else bad "$name — exit $RC: $OUT"; fi
}

# --- fixture with a full lifecycle: born -> in work -> archived -------------
new_repo
add_idea alpha "the alpha change"
git add -A
commit_msg <<'EOF'
идея alpha

Idea: alpha
EOF
git mv ideas/alpha.md changes/alpha.md 2>/dev/null || { mkdir -p changes; git mv ideas/alpha.md changes/alpha.md; }
commit_msg <<'EOF'
в работу: alpha

Change: alpha
EOF
git rm -q changes/alpha.md
commit_msg <<'EOF'
архив: alpha

Change: alpha
Archives: alpha
EOF
add_idea beta "a live idea"
git add -A
commit_msg <<'EOF'
идея beta

Idea: beta
EOF

# Default run prints all three views and writes nothing. [#render-stdout]
expect_out 'default prints plan, history and coverage [#render-stdout]'
case "$OUT" in
  *"== plan =="*"== history"*"== coverage"*) ok 'default output has all three views [#render-stdout]' ;;
  *) bad "default output misses a view: $OUT" ;;
esac
if [ -e .caped ]; then bad 'default run created .caped/ [#render-stdout]'
else ok 'default run writes nothing [#render-stdout]'; fi

# A single view prints only that view. [#render-stdout]
expect_out 'single view run succeeds [#render-stdout]' plan
case "$OUT" in
  *"== plan =="*) ok 'plan view printed [#render-stdout]' ;;
  *) bad "plan view missing: $OUT" ;;
esac
case "$OUT" in
  *"== history"*) bad "plan-only run leaked history: $OUT" ;;
  *) ok 'plan-only run has no history section [#render-stdout]' ;;
esac

# History reconstructs the archive from trailers. [#render-history]
expect_out 'history view succeeds [#render-history]' history
case "$OUT" in
  *alpha*"(was:"*) bad "unexpected rename alias: $OUT" ;;
  *alpha*) ok 'archived change listed [#render-history]' ;;
  *) bad "archived change missing: $OUT" ;;
esac
case "$OUT" in
  *"the alpha change"*) ok 'archived summary recovered [#render-history]' ;;
  *) bad "archived summary missing: $OUT" ;;
esac
case "$OUT" in
  *beta*"- idea"*) ok 'live idea status read from the filesystem [#render-history]' ;;
  *) bad "live idea row wrong: $OUT" ;;
esac

# --write materialises views with the generated header. [#render-write]
expect_out '--write succeeds [#render-write]' --write
missing=""
for f in plan.md history.md coverage.txt plan.json history.json coverage.json; do
  [ -f ".caped/$f" ] || missing="$missing $f"
done
if [ -z "$missing" ]; then ok '--write creates the text AND json forms [#render-write]'
else bad "--write missed:$missing"; fi
if head -1 .caped/plan.md | grep -q 'generated by'; then ok 'generated header present [#render-write]'
else bad 'generated header missing [#render-write]'; fi

# --clean removes the materialised views. [#render-clean]
expect_out '--clean succeeds [#render-clean]' --clean
if [ -e .caped ]; then bad '.caped/ survived --clean [#render-clean]'
else ok '--clean removes .caped/ [#render-clean]'; fi

# --- rename stitching: old name shown as (was: ...) -------------------------
new_repo
add_idea oldname "renamed idea"
git add -A
commit_msg <<'EOF'
идея oldname

Idea: oldname
EOF
git mv ideas/oldname.md ideas/newname.md
commit_msg <<'EOF'
ренейм oldname → newname

Change: init
EOF
expect_out 'history after rename succeeds [#render-history]' history
case "$OUT" in
  *newname*"(was: oldname)"*) ok 'rename stitched as (was: oldname) [#render-history]' ;;
  *) bad "rename not stitched: $OUT" ;;
esac

# --- empty repo: no ideas, no changes — still exit 0 ------------------------
new_repo
expect_out 'empty repo renders fine [#render-stdout]'
case "$OUT" in
  *"(none)"*) ok 'empty plan shows (none) [#render-stdout]' ;;
  *) bad "empty plan wrong: $OUT" ;;
esac

# --- unknown view is a usage error ------------------------------------------
set +e
OUT="$(bash "$CAPED" render bogus 2>&1)"; RC=$?
set -e
if [ "$RC" -eq 2 ]; then ok 'unknown view exits 2 [#render-stdout]'
else bad "unknown view exit $RC, want 2: $OUT"; fi

# --- adhoc decisions: fileless contract commits listed in history -----------
new_repo
echo a >> README.md; git add -A
commit_msg <<'EOF'
адхок: решение без файла

Behavior: contract
Spec: README.md
EOF
echo b >> README.md; git add -A
commit_msg <<'EOF'
внутренняя правка

Behavior: internal
EOF
echo c >> README.md; git add -A
commit_msg <<'EOF'
контракт внутри чейнджа

Behavior: contract
Change: alpha
EOF
expect_out 'history with adhoc commits succeeds [#render-history-adhoc]' history
case "$OUT" in
  *"-- adhoc decisions"*"адхок: решение без файла"*) ok 'fileless contract listed [#render-history-adhoc]' ;;
  *) bad "fileless contract missing: $OUT" ;;
esac
case "$OUT" in
  *"внутренняя правка"*) bad "internal leaked into history: $OUT" ;;
  *) ok 'internal commit not listed [#render-history-adhoc]' ;;
esac
case "$OUT" in
  *"контракт внутри чейнджа"*) bad "change-bound contract leaked into adhoc: $OUT" ;;
  *) ok 'change-bound contract not in adhoc section [#render-history-adhoc]' ;;
esac

# --- plan: last commit carries its subject; BLOCKED on unarchived deps ------
new_repo
mkdir -p ideas
cat > ideas/gamma.md <<'EOF'
---
name: gamma
summary: depends on a live idea
phase: v0
priority: high
depends_on: [delta]
---
EOF
cat > ideas/delta.md <<'EOF'
---
name: delta
summary: a live blocking idea
---
EOF
git add -A
commit_msg <<'EOF'
идеи gamma и delta

Idea: gamma
Idea: delta
EOF
expect_out 'plan with deps succeeds [#render-blocked]' plan
case "$OUT" in
  *"gamma"*"BLOCKED (dep unarchived: delta)"*) ok 'unarchived dep marks BLOCKED [#render-blocked]' ;;
  *) bad "BLOCKED marker missing: $OUT" ;;
esac
case "$OUT" in
  *"«идеи gamma и delta»"*) ok 'last: carries the commit subject [#render-stdout]' ;;
  *) bad "subject missing in last: $OUT" ;;
esac
git rm -q ideas/delta.md
commit_msg <<'EOF'
архив: delta

Change: delta
Archives: delta
EOF
expect_out 'plan after dep archival succeeds [#render-blocked]' plan
case "$OUT" in
  *"gamma"*"BLOCKED"*) bad "still blocked after the dep archived: $OUT" ;;
  *) ok 'archived dep clears BLOCKED [#render-blocked]' ;;
esac

# --- JSON mode: machine-readable form of the same view ----------------------
expect_out 'render plan --json succeeds [#render-json]' plan --json
if printf '%s' "$OUT" | python3 -c 'import json,sys; d=json.load(sys.stdin); assert d["view"]=="plan"; r=d["ideas"][0]; assert "last_commit" in r and "blocked" in r and "deps" in r' 2>/dev/null
then ok 'plan --json parses, stable keys present [#render-json]'
else bad "plan --json invalid: $OUT"; fi

# --- coverage: per-cap rows and top free paths ------------------------------
expect_out 'coverage succeeds [#render-stdout]' coverage
case "$OUT" in
  *"-- per cap --"*"root"*"enforced"*) ok 'per-cap rows present [#render-stdout]' ;;
  *) bad "per-cap rows missing: $OUT" ;;
esac
mkdir -p free/dir && echo x > free/dir/a.txt && echo y > free/dir/b.txt && git add -A && git commit -qm free
expect_out 'coverage with free files succeeds [#render-stdout]' coverage
case "$OUT" in
  *"-- top free paths --"*"free/"*) ok 'top free paths listed [#render-stdout]' ;;
  *) bad "top free paths missing: $OUT" ;;
esac

echo
echo "pass=$pass fail=$fail"
[ "$fail" -eq 0 ]
